- imageUrl: https://github.com/OctoLinker/OctoLinker/workflows/Node%20CI/badge.svg?branch=$branchName
  url: https://github.com/OctoLinker/OctoLinker/pull/$prNumber/checks
  
- imageUrl: https://badgen.net/badge/Generated%20by/%20%20%20/purple
  url: https://pullrequestbadge.com/?rel=badge